-- Misfits Street Supabase Schema

-- 1. Products Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    price INTEGER NOT NULL,
    image_url TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('TEES', 'JACKETS', 'PANTS', 'HATS', 'HOODIES')),
    size TEXT NOT NULL,
    condition TEXT NOT NULL CHECK (condition IN ('DEADSTOCK', 'EXCELLENT', 'VERY GOOD', 'GOOD', 'DISTRESSED')),
    is_sold BOOLEAN DEFAULT FALSE NOT NULL,
    is_new BOOLEAN DEFAULT FALSE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. Orders Table
CREATE TABLE public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    total_amount INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 3. Order Items Table
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    price_at_purchase INTEGER NOT NULL
);

-- Row Level Security (RLS)

-- Products: Anyone can read, only authenticated users with an "admin" flag (to be defined in app logic or custom claims) can mutate.
-- For simplicity, since verifying admin via SQL requires custom claims or a profiles table, 
-- we will enforce admin checks at the Next.js Server Action level.
-- But we can lock down mutations to authenticated users broadly here as a baseline.
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access to products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Auth mutate access to products" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- Orders: Users can read their own orders. Admins (authenticated) can mutate.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Auth mutate access to orders" ON public.orders FOR ALL USING (auth.role() = 'authenticated');

-- Order Items: Users read items belonging to their orders.
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own order items" ON public.order_items FOR SELECT USING (
    order_id IN (SELECT id FROM public.orders WHERE user_id = auth.uid())
);
CREATE POLICY "Auth mutate access to order items" ON public.order_items FOR ALL USING (auth.role() = 'authenticated');
